[versions]
android-sdk-min = "26"
android-sdk-target = "35"
android-sdk-compile = "35"
agp = "8.10.1"
kotlin = "2.1.21"
core-ktx = "1.16.0"
junit = "4.13.2"
appcompat = "1.7.1"
material = "1.12.0"
material3 = "1.3.0"
compose-bom = "2025.06.00"
compose-activity = "1.10.1"
compose-compiler = "1.5.15"
compose-navigation = "2.8.9"
compose-lifecycle = "2.9.1"
google-services = "4.4.2"
firebase-appdistribution = "5.1.1"
ktlint = "12.1.0"
paparazzi = "1.3.5"
dagger-hilt = "2.56.2"
dagger-hilt-compose-navigation = "1.2.0"
ksp = "2.1.21-2.0.2"
dagger = "5.0.1"
okhttp = "4.12.0"
chucker = "4.0.0"
retrofit = "2.11.0"
moshi = "1.15.1"
moshi-sealed = "0.28.0"
kotlinx-coroutines = "1.10.2"
turbine = "1.1.0"
androidx-browser = "1.8.0"
datastore = "1.1.7"
androidx-test-core = "1.6.1"
androidx-junit = "1.2.1"
androidx-test-runner = "1.6.2"
okhttp-mockwebserver = "4.12.0"
okio = "3.11.0"
espresso-intents = "3.6.1"
sonarqube = "6.0.1.5171"
lokalise = "5.2.0"
json = "20210307"
rootbeer = "0.1.0"
mockk = "1.13.11"
j2v8 = "6.2.1"
bcrypt = "0.4"
biometric = "1.4.0-alpha02"
security-crypto = "1.0.0"
kotlinx-serialization-json = "1.8.0"
kover = "0.9.1"
robolectric = "4.14.1"
lifecycle-process = "2.9.1"
json-kotlin-schema-codegen = "0.115"
ui-test-junit4-android = "1.8.2"
about-libraries = "11.6.3"
bcutil = "1.79"
itext7 = "9.2.0"
zoomable = "2.8.0"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
compose-material3 = { group = "androidx.compose.material3", name = "material3" }
compose-material-icons-core = { group = "androidx.compose.material", name = "material-icons-core" }
compose-material-icons-extended = { group = "androidx.compose.material", name = "material-icons-extended" }
compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
compose-activity = { group = "androidx.activity", name = "activity-compose", version.ref = "compose-activity" }
compose-lifecycle = { group = "androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "compose-lifecycle" }
compose-navigation = { group = "androidx.navigation", name = "navigation-compose", version.ref = "compose-navigation" }
paparazzi = { group = "app.cash.paparazzi", name = "paparazzi", version.ref = "paparazzi" }
dagger-hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "dagger-hilt" }
dagger-hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "dagger-hilt" }
dagger-hilt-compose-navigation = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "dagger-hilt-compose-navigation" }
dagger-hilt-testing = { group = "com.google.dagger", name = "hilt-android-testing", version.ref = "dagger-hilt" }
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "dagger" }
okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
chucker = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
chucker-no-op = { group = "com.github.chuckerteam.chucker", name = "library", version.ref = "chucker" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-kotlinx-serialization-converter = { group = "com.squareup.retrofit2", name = "converter-kotlinx-serialization", version.ref ="retrofit" }
androidx-browser = { group = "androidx.browser", name = "browser", version.ref = "androidx-browser" }
coroutines-bom = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-bom", version.ref = "kotlinx-coroutines" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core" }
coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android" }
coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test" }
turbine = { module = "app.cash.turbine:turbine", version.ref = "turbine" }
datastore-preference = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }
androidx-test-core = { group = "androidx.test", name = "core-ktx", version.ref = "androidx-test-core" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
androidx-test-runner = { group = "androidx.test", name = "runner", version.ref = "androidx-test-runner" }
okhttp-mockwebserver = { group = "com.squareup.okhttp3", name = "mockwebserver", version.ref = "okhttp-mockwebserver" }
okio = { group = "com.squareup.okio", name = "okio", version.ref = "okio" }
espresso-intents = { group = "androidx.test.espresso", name = "espresso-intents", version.ref = "espresso-intents" }
lokalise = { group = "com.lokalise", name = "lokalise-api-java", version.ref = "lokalise" }
json = { group = "org.json", name = "json", version.ref = "json" }
rootbeer = { group = "com.scottyab", name = "rootbeer-lib", version.ref = "rootbeer" }
mockk-android = { group = "io.mockk", name = "mockk-android", version.ref = "mockk" }
j2v8 = { group = "com.eclipsesource.j2v8", name = "j2v8", version.ref = "j2v8" }
bcrypt = { group = "org.mindrot", name = "jbcrypt", version.ref = "bcrypt" }
biometric = { group = "androidx.biometric", name = "biometric-ktx", version.ref = "biometric" }
androidx-security-crypto = { group = "androidx.security", name = "security-crypto", version.ref = "security-crypto" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization-json" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }
robolectric = { group = "org.robolectric", name = "robolectric", version.ref = "robolectric" }
androidx-lifecycle-process = { group = "androidx.lifecycle", name = "lifecycle-process", version.ref = "lifecycle-process" }
json-kotlin-schema-codegen = { group = "net.pwall.json", name = "json-kotlin-schema-codegen", version.ref = "json-kotlin-schema-codegen" }
androidx-ui-test-junit4-android = { group = "androidx.compose.ui", name = "ui-test-junit4-android", version.ref = "ui-test-junit4-android" }
aboutlibraries-compose = { group = "com.mikepenz", name = "aboutlibraries-compose", version.ref = "about-libraries" }
bcutil = { group = "org.bouncycastle", name = "bcutil-jdk18on", version.ref = "bcutil"}
itext7-core = { group = "com.itextpdf", name = "itext7-core", version.ref = "itext7"}
zoomable = { group = "net.engawapg.lib", name = "zoomable", version.ref = "zoomable" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebaseAppdistribution = { id = "com.google.firebase.appdistribution", version.ref = "firebase-appdistribution" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
paparazzi = { id = "app.cash.paparazzi", version.ref = "paparazzi" }
daggerHilt = { id = "com.google.dagger.hilt.android", version.ref = "dagger-hilt" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
sonarqube = { id = "org.sonarqube", version.ref = "sonarqube" }
serializable = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kover" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin", version.ref = "about-libraries"}
